/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VariablePanel.java
 *
 * Created on Nov 24, 2010, 5:41:59 PM
 */

package carneades.editor.uicomponents.wizards.instantiatescheme;

/**
 *
 * @author pal
 */
public class VariablePanel extends javax.swing.JPanel {

    /** Creates new form VariablePanel */
    public VariablePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        variableLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 50));

        variableLabel.setText("Variable:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(variableLabel)
                .addGap(6, 6, 6)
                .addComponent(variableText, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variableText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(variableLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel variableLabel;
    public final javax.swing.JTextField variableText = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables

}
