
package org.fokus.carneades;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CarneadesServiceManagerService", targetNamespace = "http://carneades.fokus.org/", wsdlLocation = "http://localhost:8080/carneadesws/CarneadesServiceManager?wsdl")
public class CarneadesServiceManagerService
    extends Service
{

    private final static URL CARNEADESSERVICEMANAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.fokus.carneades.CarneadesServiceManagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.fokus.carneades.CarneadesServiceManagerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/carneadesws/CarneadesServiceManager?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/carneadesws/CarneadesServiceManager?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CARNEADESSERVICEMANAGERSERVICE_WSDL_LOCATION = url;
    }

    public CarneadesServiceManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarneadesServiceManagerService() {
        super(CARNEADESSERVICEMANAGERSERVICE_WSDL_LOCATION, new QName("http://carneades.fokus.org/", "CarneadesServiceManagerService"));
    }

    /**
     * 
     * @return
     *     returns CarneadesService
     */
    @WebEndpoint(name = "CarneadesServiceManagerPort")
    public CarneadesService getCarneadesServiceManagerPort() {
        return super.getPort(new QName("http://carneades.fokus.org/", "CarneadesServiceManagerPort"), CarneadesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarneadesService
     */
    @WebEndpoint(name = "CarneadesServiceManagerPort")
    public CarneadesService getCarneadesServiceManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://carneades.fokus.org/", "CarneadesServiceManagerPort"), CarneadesService.class, features);
    }

}
