
package org.fokus.carneades;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CarneadesService", targetNamespace = "http://carneades.fokus.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarneadesService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.fokus.carneades.CarneadesMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "askEngine", targetNamespace = "http://carneades.fokus.org/", className = "org.fokus.carneades.AskEngine")
    @ResponseWrapper(localName = "askEngineResponse", targetNamespace = "http://carneades.fokus.org/", className = "org.fokus.carneades.AskEngineResponse")
    public CarneadesMessage askEngine(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
