/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchemesPanel.java
 *
 * Created on Nov 17, 2010, 3:38:01 PM
 */

package carneades.editor.uicomponents.wizards.formalizestatement;

import carneades.editor.uicomponents.wizards.instantiatescheme.*;

/**
 *
 * @author pal
 */
public class StatementPanel extends javax.swing.JPanel {

    /** Creates new form SchemesPanel */
    public StatementPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 471));

        statementTextArea.setBackground(new java.awt.Color(222, 222, 222));
        statementTextArea.setColumns(20);
        statementTextArea.setEditable(false);
        statementTextArea.setLineWrap(true);
        statementTextArea.setRows(5);
        statementTextArea.setWrapStyleWord(true);
        statementTextArea.setMinimumSize(new java.awt.Dimension(0, 50));
        statementTextArea.setPreferredSize(new java.awt.Dimension(260, 100));

        jLabel1.setText("Statement to formalize:");

        literalPanel.setMinimumSize(new java.awt.Dimension(167, 360));
        literalPanel.setLayout(new javax.swing.BoxLayout(literalPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(literalPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(statementTextArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statementTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(literalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public final javax.swing.JPanel literalPanel = new javax.swing.JPanel();
    public final javax.swing.JTextArea statementTextArea = new javax.swing.JTextArea();
    // End of variables declaration//GEN-END:variables

}
