/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProponentPanel.java
 *
 * Created on Oct 19, 2010, 3:43:25 PM
 */

package carneades.editor.uicomponents.wizards.goal;

/**
 *
 * @author pal
 */
public class ProponentPanel extends javax.swing.JPanel {

    /** Creates new form ProponentPanel */
    public ProponentPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pointOfView = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jLabel1.setText("The main issue is:");

        mainIssueTextArea.setBackground(new java.awt.Color(222, 222, 222));
        mainIssueTextArea.setColumns(20);
        mainIssueTextArea.setEditable(false);
        mainIssueTextArea.setLineWrap(true);
        mainIssueTextArea.setRows(5);
        mainIssueTextArea.setWrapStyleWord(true);
        mainIssueTextArea.setMinimumSize(new java.awt.Dimension(0, 50));
        mainIssueTextArea.setPreferredSize(new java.awt.Dimension(260, 100));

        jLabel2.setText("What is your point of view? I am a...");

        pointOfView.add(jRadioButton1);
        jRadioButton1.setText("Proponent");
        jRadioButton1.setName("proponent"); // NOI18N

        pointOfView.add(jRadioButton2);
        jRadioButton2.setText("Opponent");
        jRadioButton2.setName("opponent"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(274, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainIssueTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addGap(152, 152, 152))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addContainerGap(298, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addContainerGap(301, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainIssueTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    public final javax.swing.JTextArea mainIssueTextArea = new javax.swing.JTextArea();
    private javax.swing.ButtonGroup pointOfView;
    // End of variables declaration//GEN-END:variables

    // our modifications:
    public static ProponentPanel panelInstance = new ProponentPanel();

    public static synchronized ProponentPanel instance()
    {
        return panelInstance;
    }

    public static synchronized void reset()
    {
        panelInstance = new ProponentPanel();
    }
}
