/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PremisePropertiesView.java
 *
 * Created on Aug 27, 2010, 3:20:08 PM
 */

package carneades.editor.uicomponents;

/**
 *
 * @author pal
 */
public class PremisePropertiesView extends javax.swing.JPanel {

    /** Creates new form PremisePropertiesView */
    public PremisePropertiesView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proConGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        proConGroup.add(proButton);
        proButton.setText("Pro");

        proConGroup.add(conButton);
        conButton.setText("Con");

        jLabel1.setText("Type:");

        jLabel2.setText("Polarity:");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordinary premise", "Assumption", "Exception" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(proButton)
                        .addGap(12, 12, 12)
                        .addComponent(conButton))
                    .addComponent(typeComboBox, 0, 170, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proButton)
                    .addComponent(jLabel2)
                    .addComponent(conButton))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JRadioButton conButton = new javax.swing.JRadioButton();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public final javax.swing.JRadioButton proButton = new javax.swing.JRadioButton();
    private javax.swing.ButtonGroup proConGroup;
    public final javax.swing.JComboBox typeComboBox = new javax.swing.JComboBox();
    // End of variables declaration//GEN-END:variables

    // our modifications:
    public static PremisePropertiesView viewInstance = new PremisePropertiesView();

    public static synchronized PremisePropertiesView instance()
    {
        return viewInstance;
    }

    public static synchronized void reset()
    {
        viewInstance = new PremisePropertiesView();
    }
}
